### ISSUE TITLE
search init找不到config文件

### ISSUE THREAD

**Issue by sairson** [Rvn0xsy/red-tldr#1]
我在search init时抛出错误panic: Fatal error config file: Config File "config" Not Found ，我该如何解决

**Comment by Rvn0xsy** [comment]
该问题已经复现，马上解决。

临时解决办法：将本仓库中的 config/config.toml 拷贝到当前用户的HOME目录下

**Comment by Rvn0xsy** [comment]
> 我在search init时抛出错误panic: Fatal error config file: Config File "config" Not Found ，我该如何解决

该问题已经复现，马上解决。

临时解决办法：将本仓库中的 config/config.toml 拷贝到当前用户的HOME目录下

**Comment by Rvn0xsy** [comment]
这个版本已经解决此问题，请下载新版本：https://github.com/Rvn0xsy/red-tldr/releases/tag/v0.3
