### ISSUE TITLE
Window平台下main.go的viper.ReadInConfig()函数存在兼容问题

### ISSUE THREAD

**Issue by Tomassky** [Rvn0xsy/red-tldr#4]
viper.ReadInConfig()这个函数会一直判断当前目录下是否有存在config文件，不存在则会进入生成根目录下的config文件，导致第一次执行没问题，第二次执行的时候因为存在.red-tldr文件夹，进而第二次mkdir会报错

**Comment by Rvn0xsy** [comment]
在版本v0.4中已经修复此问题，兼容Windows平台，欢迎进行测试
