### ISSUE TITLE
我最新版咋个和你不一样

### ISSUE THREAD

**Issue by Laura0xiaoshizi** [Rvn0xsy/red-tldr#5]
<img width="572" alt="图片" src="https://user-images.githubusercontent.com/31725824/129175809-fcea3cc8-c9b5-45fb-945f-d4d8f8b40c88.png">
我的内容为啥少些

**Comment by Rvn0xsy** [comment]
> <img alt="图片" width="572" src="https://user-images.githubusercontent.com/31725824/129175809-fcea3cc8-c9b5-45fb-945f-d4d8f8b40c88.png">
> 
> 我的内容为啥少些

是下载的0.4版本么？

**Comment by Laura0xiaoshizi** [comment]
> > <img alt="图片" width="572" src="https://user-images.githubusercontent.com/31725824/129175809-fcea3cc8-c9b5-45fb-945f-d4d8f8b40c88.png">
> > 我的内容为啥少些
> 
> 是下载的0.4版本么？

是的啊，不过我下的你编译好的，我本地编译有问题。

**Comment by Rvn0xsy** [comment]
如果是 0.4 版本，所有用户的数据都是与https://github.com/Rvn0xsy/red-tldr-db同步的。

可以使用如下命令进行手动同步：

```
$ red-tldr update
```
